<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ["governorate_id"=>"1","city"=>"15 May"],
            ["governorate_id"=>"1","city"=>"Al Azbakeyah"],
            ["governorate_id"=>"1","city"=>"Al Basatin"],
            ["governorate_id"=>"1","city"=>"Tebin"],
            ["governorate_id"=>"1","city"=>"El-Khalifa"],
            ["governorate_id"=>"1","city"=>"El darrasa"],
            ["governorate_id"=>"1","city"=>"Aldarb Alahmar"],
            ["governorate_id"=>"1","city"=>"Zawya al-Hamra"],
            ["governorate_id"=>"1","city"=>"El-Zaytoun"],
            ["governorate_id"=>"1","city"=>"Sahel"],
            ["governorate_id"=>"1","city"=>"El Salam"],
            ["governorate_id"=>"1","city"=>"Sayeda Zeinab"],
            ["governorate_id"=>"1","city"=>"El Sharabeya"],
            ["governorate_id"=>"1","city"=>"Shorouk"],
            ["governorate_id"=>"1","city"=>"El Daher"],
            ["governorate_id"=>"1","city"=>"Ataba"],
            ["governorate_id"=>"1","city"=>"New Cairo"],
            ["governorate_id"=>"1","city"=>"El Marg"],
            ["governorate_id"=>"1","city"=>"Ezbet el Nakhl"],
            ["governorate_id"=>"1","city"=>"Matareya"],
            ["governorate_id"=>"1","city"=>"Maadi"],
            ["governorate_id"=>"1","city"=>"Maasara"],
            ["governorate_id"=>"1","city"=>"Mokattam"],
            ["governorate_id"=>"1","city"=>"Manyal"],
            ["governorate_id"=>"1","city"=>"Mosky"],
            ["governorate_id"=>"1","city"=>"Nozha"],
            ["governorate_id"=>"1","city"=>"Waily"],
            ["governorate_id"=>"1","city"=>"Bab al-Shereia"],
            ["governorate_id"=>"1","city"=>"Bolaq"],
            ["governorate_id"=>"1","city"=>"Garden City"],
            ["governorate_id"=>"1","city"=>"Hadayek El-Kobba"],
            ["governorate_id"=>"1","city"=>"Helwan"],
            ["governorate_id"=>"1","city"=>"Dar Al Salam"],
            // ["governorate_id"=>"1","city_name_ar"=>"شبرا","city"=>"Shubra"],
            // ["governorate_id"=>"1","city_name_ar"=>"طره","city"=>"Tura"],
            // ["governorate_id"=>"1","city_name_ar"=>"عابدين","city"=>"Abdeen"],
            // ["governorate_id"=>"1","city_name_ar"=>"عباسية","city"=>"Abaseya"],
            // ["governorate_id"=>"1","city_name_ar"=>"عين شمس","city"=>"Ain Shams"],
            // ["governorate_id"=>"1","city_name_ar"=>"مدينة نصر","city"=>"Nasr City"],
            // ["governorate_id"=>"1","city_name_ar"=>"مصر الجديدة","city"=>"New Heliopolis"],
            ["governorate_id"=>"1", "city"=>"Masr Al Qadima"],
            ["governorate_id"=>"1","city"=>"Mansheya Nasir"],
            ["governorate_id"=>"1","city"=>"Badr City"],
            ["governorate_id"=>"1","city"=>"Obour City"],
            ["governorate_id"=>"1","city"=>"Cairo Downtown"],
            ["governorate_id"=>"1","city"=>"Zamalek"],
            ["governorate_id"=>"1","city"=>"Kasr El Nile"],
            ["governorate_id"=>"1","city"=>"Rehab"],
            ["governorate_id"=>"1","city"=>"Katameya"],
            ["governorate_id"=>"1","city"=>"Madinty"],
            ["governorate_id"=>"1","city"=>"Rod Alfarag"],
            ["governorate_id"=>"1","city"=>"Sheraton"],
            ["governorate_id"=>"1","city"=>"El-Gamaleya"],
            ["governorate_id"=>"1","city"=>"10th of Ramadan City"],
            ["governorate_id"=>"1","city"=>"Helmeyat Alzaytoun"],
            ["governorate_id"=>"1","city"=>"New Nozha"],
            ["governorate_id"=>"1","city"=>"Capital New"],
            ["governorate_id"=>"2","city"=>"Giza"],
            ["governorate_id"=>"2","city"=>"Sixth of October"],
            ["governorate_id"=>"2","city"=>"Cheikh Zayed"],
            ["governorate_id"=>"2","city"=>"Hawamdiyah"],
            ["governorate_id"=>"2","city"=>"Al Badrasheen"],
            // ["governorate_id"=>"2",ف","city"=>"Saf"],
            // ["governorate_id"=>"2",يح","city"=>"Atfih"],
            // ["governorate_id"=>"2",ياط","city"=>"Al Ayat"],
            // ["governorate_id"=>"2",اويطي","city"=>"Al-Bawaiti"],
            // ["governorate_id"=>"2",أة القناطر","city"=>"ManshiyetAl Qanater"],
            // ["governorate_id"=>"2",يم","city"=>"Oaseem"],
            // ["governorate_id"=>"2",اسة","city"=>"Kerdasa"],
            // ["governorate_id"=>"2", النمرس","city"=>"Abu Nomros"],
            // ["governorate_id"=>"2", غطاطي","city"=>"Kafr Ghati"],
            // ["governorate_id"=>"2",أة البكاري","city"=>"Manshiyet Al Bakari"],
            // ["governorate_id"=>"2",قى","city"=>"Dokki"],
            // ["governorate_id"=>"2",جوزة","city"=>"Agouza"],
            // ["governorate_id"=>"2",رم","city"=>"Haram"],
            // ["governorate_id"=>"2",راق","city"=>"Warraq"],
            // ["governorate_id"=>"2",ابة","city"=>"Imbaba"],
            // ["governorate_id"=>"2",اق الدكرور","city"=>"Boulaq Dakrour"],
            // ["governorate_id"=>"2",احات البحرية","city"=>"Al Wahat Al Baharia"],
            // ["governorate_id"=>"2",مرانية","city"=>"Omraneya"],
            // ["governorate_id"=>"2",نيب","city"=>"Moneeb"],
            // ["governorate_id"=>"2", السرايات","city"=>"Bin Alsarayat"],
            // ["governorate_id"=>"2",يت كات","city"=>"Kit Kat"],
            // ["governorate_id"=>"2",هندسين","city"=>"Mohandessin"],
            // ["governorate_id"=>"2",ل","city"=>"Faisal"],
            // ["governorate_id"=>"2", رواش","city"=>"Abu Rawash"],
            // ["governorate_id"=>"2",ئق الأهرام","city"=>"Hadayek Alahram"],
            // ["governorate_id"=>"2",رانية","city"=>"Haraneya"],
            // ["governorate_id"=>"2",ئق اكتوبر","city"=>"Hadayek October"],
            // ["governorate_id"=>"2", اللبن","city"=>"Saft Allaban"],
            // ["governorate_id"=>"2",رية الذكية","city"=>"Smart Village"],
            // ["governorate_id"=>"2", اللواء","city"=>"Ard Ellwaa"],
            ["governorate_id"=>"3","city"=>"Abu Qir"],
            ["governorate_id"=>"3","city"=>"Al Ibrahimeyah"],
            ["governorate_id"=>"3","city"=>"Azarita"],
            ["governorate_id"=>"3","city"=>"Anfoushi"],
            ["governorate_id"=>"3","city"=>"Dekheila"],
            ["governorate_id"=>"3","city"=>"El Soyof"],
            ["governorate_id"=>"3","city"=>"Ameria"],
            // ["id"=>"100","governorate_id"=>"3","city_name_ar"=>"اللبان","city"=>"El Labban"],
            // ["id"=>"101","governorate_id"=>"3","city_name_ar"=>"المفروزة","city"=>"Al Mafrouza"],
            // ["id"=>"102","governorate_id"=>"3","city_name_ar"=>"المنتزه","city"=>"El Montaza"],
            // ["id"=>"103","governorate_id"=>"3","city_name_ar"=>"المنشية","city"=>"Mansheya"],
            // ["id"=>"104","governorate_id"=>"3","city_name_ar"=>"الناصرية","city"=>"Naseria"],
            // ["id"=>"105","governorate_id"=>"3","city_name_ar"=>"امبروزو","city"=>"Ambrozo"],
            // ["id"=>"106","governorate_id"=>"3","city_name_ar"=>"باب شرق","city"=>"Bab Sharq"],
            // ["id"=>"107","governorate_id"=>"3","city_name_ar"=>"برج العرب","city"=>"Bourj Alarab"],
            // ["id"=>"108","governorate_id"=>"3","city_name_ar"=>"ستانلى","city"=>"Stanley"],
            // ["id"=>"109","governorate_id"=>"3","city_name_ar"=>"سموحة","city"=>"Smouha"],
            // ["id"=>"110","governorate_id"=>"3","city_name_ar"=>"سيدى بشر","city"=>"Sidi Bishr"],
            // ["id"=>"111","governorate_id"=>"3","city_name_ar"=>"شدس","city"=>"Shads"],
            // ["id"=>"112","governorate_id"=>"3","city_name_ar"=>"غيط العنب","city"=>"Gheet Alenab"],
            // ["id"=>"113","governorate_id"=>"3","city_name_ar"=>"فلمينج","city"=>"Fleming"],
            // ["id"=>"114","governorate_id"=>"3","city_name_ar"=>"فيكتوريا","city"=>"Victoria"],
            // ["id"=>"115","governorate_id"=>"3","city_name_ar"=>"كامب شيزار","city"=>"Camp Shizar"],
            // ["id"=>"116","governorate_id"=>"3","city_name_ar"=>"كرموز","city"=>"Karmooz"],
            // ["id"=>"117","governorate_id"=>"3","city_name_ar"=>"محطة الرمل","city"=>"Mahta Alraml"],
            // ["id"=>"118","governorate_id"=>"3","city_name_ar"=>"مينا البصل","city"=>"Mina El-Basal"],
            // ["id"=>"119","governorate_id"=>"3","city_name_ar"=>"العصافرة","city"=>"Asafra"],
            // ["id"=>"120","governorate_id"=>"3","city_name_ar"=>"العجمي","city"=>"Agamy"],
            // ["id"=>"121","governorate_id"=>"3","city_name_ar"=>"بكوس","city"=>"Bakos"],
            // ["id"=>"122","governorate_id"=>"3","city_name_ar"=>"بولكلي","city"=>"Boulkly"],
            // ["id"=>"123","governorate_id"=>"3","city_name_ar"=>"كليوباترا","city"=>"Cleopatra"],
            // ["id"=>"124","governorate_id"=>"3","city_name_ar"=>"جليم","city"=>"Glim"],
            // ["id"=>"125","governorate_id"=>"3","city_name_ar"=>"المعمورة","city"=>"Al Mamurah"],
            // ["id"=>"126","governorate_id"=>"3","city_name_ar"=>"المندرة","city"=>"Al Mandara"],
            // ["id"=>"127","governorate_id"=>"3","city_name_ar"=>"محرم بك","city"=>"Moharam Bek"],
            // ["id"=>"128","governorate_id"=>"3","city_name_ar"=>"الشاطبي","city"=>"Elshatby"],
            // ["id"=>"129","governorate_id"=>"3","city_name_ar"=>"سيدي جابر","city"=>"Sidi Gaber"],
            // ["id"=>"130","governorate_id"=>"3","city_name_ar"=>"الساحل الشمالي","city"=>"North Coast\/sahel"],
            // ["id"=>"131","governorate_id"=>"3","city_name_ar"=>"الحضرة","city"=>"Alhadra"],
            // ["id"=>"132","governorate_id"=>"3","city_name_ar"=>"العطارين","city"=>"Alattarin"],
            // ["id"=>"133","governorate_id"=>"3","city_name_ar"=>"سيدي كرير","city"=>"Sidi Kerir"],
            // ["id"=>"134","governorate_id"=>"3","city_name_ar"=>"الجمرك","city"=>"Elgomrok"],
            // ["id"=>"135","governorate_id"=>"3","city_name_ar"=>"المكس","city"=>"Al Max"],
            // ["id"=>"136","governorate_id"=>"3","city_name_ar"=>"مارينا","city"=>"Marina"],
            // ["id"=>"137","governorate_id"=>"4","city_name_ar"=>"المنصورة","city"=>"Mansoura"],
            // ["id"=>"138","governorate_id"=>"4","city_name_ar"=>"طلخا","city"=>"Talkha"],
            // ["id"=>"139","governorate_id"=>"4","city_name_ar"=>"ميت غمر","city"=>"Mitt Ghamr"],
            // ["id"=>"140","governorate_id"=>"4","city_name_ar"=>"دكرنس","city"=>"Dekernes"],
            // ["id"=>"141","governorate_id"=>"4","city_name_ar"=>"أجا","city"=>"Aga"],
            // ["id"=>"142","governorate_id"=>"4","city_name_ar"=>"منية النصر","city"=>"Menia El Nasr"],
            // ["id"=>"143","governorate_id"=>"4","city_name_ar"=>"السنبلاوين","city"=>"Sinbillawin"],
            // ["id"=>"144","governorate_id"=>"4","city_name_ar"=>"الكردي","city"=>"El Kurdi"],
            // ["id"=>"145","governorate_id"=>"4","city_name_ar"=>"بني عبيد","city"=>"Bani Ubaid"],
            // ["id"=>"146","governorate_id"=>"4","city_name_ar"=>"المنزلة","city"=>"Al Manzala"],
            // ["id"=>"147","governorate_id"=>"4","city_name_ar"=>"تمي الأمديد","city"=>"tami al'amdid"],
            // ["id"=>"148","governorate_id"=>"4","city_name_ar"=>"الجمالية","city"=>"aljamalia"],
            ["governorate_id"=>"4","city"=>"Sherbin"],
            // ["governorate_id"=>"4""بلقاس","city"=>"Belqas"],
            // ["governorate_id"=>"4""ميت سلسيل","city"=>"Meet Salsil"],
            // ["governorate_id"=>"4""جمصة","city"=>"Gamasa"],
            // ["governorate_id"=>"4""محلة دمنة","city"=>"Mahalat Damana"],
            // ["id"=>"155","governorate_id"=>"4","city_name_ar"=>"نبروه","city"=>"Nabroh"],
            // ["id"=>"156","governorate_id"=>"5","city_name_ar"=>"الغردقة","city"=>"Hurghada"],
            // ["id"=>"157","governorate_id"=>"5","city_name_ar"=>"رأس غارب","city"=>"Ras Ghareb"],
            ["governorate_id"=>"5","city"=>"Safaga"],
            // ["id"=>"159","governorate_id"=>"5","city_name_ar"=>"القصير","city"=>"El Qusiar"],
            // ["id"=>"160","governorate_id"=>"5","city_name_ar"=>"مرسى علم","city"=>"Marsa Alam"],
            // ["id"=>"161","governorate_id"=>"5","city_name_ar"=>"الشلاتين","city"=>"Shalatin"],
            // ["id"=>"162","governorate_id"=>"5","city_name_ar"=>"حلايب","city"=>"Halaib"],
            // ["id"=>"163","governorate_id"=>"5","city_name_ar"=>"الدهار","city"=>"Aldahar"],
            // ["id"=>"164","governorate_id"=>"6","city_name_ar"=>"دمنهور","city"=>"Damanhour"],
            // ["id"=>"165","governorate_id"=>"6","city_name_ar"=>"كفر الدوار","city"=>"Kafr El Dawar"],
            ["governorate_id"=>"6","city"=>"Rashid"],
            // ["id"=>"167","governorate_id"=>"6","city_name_ar"=>"إدكو","city"=>"Edco"],
            // ["id"=>"168","governorate_id"=>"6","city_name_ar"=>"أبو المطامير","city"=>"Abu al-Matamir"],
            // ["id"=>"169","governorate_id"=>"6","city_name_ar"=>"أبو حمص","city"=>"Abu Homs"],
            // ["id"=>"170","governorate_id"=>"6","city_name_ar"=>"الدلنجات","city"=>"Delengat"],
            // ["id"=>"171","governorate_id"=>"6","city_name_ar"=>"المحمودية","city"=>"Mahmoudiyah"],
            // ["id"=>"172","governorate_id"=>"6","city_name_ar"=>"الرحمانية","city"=>"Rahmaniyah"],
            // ["id"=>"173","governorate_id"=>"6","city_name_ar"=>"إيتاي البارود","city"=>"Itai Baroud"],
            // ["id"=>"174","governorate_id"=>"6","city_name_ar"=>"حوش عيسى","city"=>"Housh Eissa"],
            // ["id"=>"175","governorate_id"=>"6","city_name_ar"=>"شبراخيت","city"=>"Shubrakhit"],
            // ["id"=>"176","governorate_id"=>"6","city_name_ar"=>"كوم حمادة","city"=>"Kom Hamada"],
            // ["id"=>"177","governorate_id"=>"6","city_name_ar"=>"بدر","city"=>"Badr"],
            // ["id"=>"178","governorate_id"=>"6","city_name_ar"=>"وادي النطرون","city"=>"Wadi Natrun"],
            // ["id"=>"179","governorate_id"=>"6","city_name_ar"=>"النوبارية الجديدة","city"=>"New Nubaria"],
            // ["id"=>"180","governorate_id"=>"6","city_name_ar"=>"النوبارية","city"=>"Alnoubareya"],
            // ["id"=>"181","governorate_id"=>"7","city_name_ar"=>"الفيوم","city"=>"Fayoum"],
            // ["id"=>"182","governorate_id"=>"7","city_name_ar"=>"الفيوم الجديدة","city"=>"Fayoum El Gedida"],
            ["governorate_id"=>"7","city"=>"Tamiya"],
            // ["id"=>"184","governorate_id"=>"7","city_name_ar"=>"سنورس","city"=>"Snores"],
            // ["id"=>"185","governorate_id"=>"7","city_name_ar"=>"إطسا","city"=>"Etsa"],
            // ["id"=>"186","governorate_id"=>"7","city_name_ar"=>"إبشواي","city"=>"Epschway"],
            // ["id"=>"187","governorate_id"=>"7","city_name_ar"=>"يوسف الصديق","city"=>"Yusuf El Sediaq"],
            // ["id"=>"188","governorate_id"=>"7","city_name_ar"=>"الحادقة","city"=>"Hadqa"],
            // ["id"=>"189","governorate_id"=>"7","city_name_ar"=>"اطسا","city"=>"Atsa"],
            // ["id"=>"190","governorate_id"=>"7","city_name_ar"=>"الجامعة","city"=>"Algamaa"],
            // ["id"=>"191","governorate_id"=>"7","city_name_ar"=>"السيالة","city"=>"Sayala"],
            // ["id"=>"192","governorate_id"=>"8","city_name_ar"=>"طنطا","city"=>"Tanta"],
            // ["id"=>"193","governorate_id"=>"8","city_name_ar"=>"المحلة الكبرى","city"=>"Al Mahalla Al Kobra"],
            // ["id"=>"194","governorate_id"=>"8","city_name_ar"=>"كفر الزيات","city"=>"Kafr El Zayat"],
            // ["id"=>"195","governorate_id"=>"8","city_name_ar"=>"زفتى","city"=>"Zefta"],
            // ["id"=>"196","governorate_id"=>"8","city_name_ar"=>"السنطة","city"=>"El Santa"],
            // ["id"=>"197","governorate_id"=>"8","city_name_ar"=>"قطور","city"=>"Qutour"],
            // ["id"=>"198","governorate_id"=>"8","city_name_ar"=>"بسيون","city"=>"Basion"],
            // ["id"=>"199","governorate_id"=>"8","city_name_ar"=>"سمنود","city"=>"Samannoud"],
            // ["id"=>"200","governorate_id"=>"9","city_name_ar"=>"الإسماعيلية","city"=>"Ismailia"],
            // ["id"=>"201","governorate_id"=>"9","city_name_ar"=>"فايد","city"=>"Fayed"],
            // ["id"=>"202","governorate_id"=>"9","city_name_ar"=>"القنطرة شرق","city"=>"Qantara Sharq"],
            // ["id"=>"203","governorate_id"=>"9","city_name_ar"=>"القنطرة غرب","city"=>"Qantara Gharb"],
            // ["id"=>"204","governorate_id"=>"9","city_name_ar"=>"التل الكبير","city"=>"El Tal El Kabier"],
            // ["id"=>"205","governorate_id"=>"9","city_name_ar"=>"أبو صوير","city"=>"Abu Sawir"],
            // ["id"=>"206","governorate_id"=>"9","city_name_ar"=>"القصاصين الجديدة","city"=>"Kasasien El Gedida"],
            // ["id"=>"207","governorate_id"=>"9","city_name_ar"=>"نفيشة","city"=>"Nefesha"],
            // ["id"=>"208","governorate_id"=>"9","city_name_ar"=>"الشيخ زايد","city"=>"Sheikh Zayed"],
            // ["id"=>"209","governorate_id"=>"10","city_name_ar"=>"شبين الكوم","city"=>"Shbeen El Koom"],
            // ["id"=>"210","governorate_id"=>"10","city_name_ar"=>"مدينة السادات","city"=>"Sadat City"],
            // ["id"=>"211","governorate_id"=>"10","city_name_ar"=>"منوف","city"=>"Menouf"],
            // ["id"=>"212","governorate_id"=>"10","city_name_ar"=>"سرس الليان","city"=>"Sars El-Layan"],
            // ["id"=>"213","governorate_id"=>"10","city_name_ar"=>"أشمون","city"=>"Ashmon"],
            // ["id"=>"214","governorate_id"=>"10","city_name_ar"=>"الباجور","city"=>"Al Bagor"],
            // ["id"=>"215","governorate_id"=>"10","city_name_ar"=>"قويسنا","city"=>"Quesna"],
            // ["id"=>"216","governorate_id"=>"10","city_name_ar"=>"بركة السبع","city"=>"Berkat El Saba"],
            // ["id"=>"217","governorate_id"=>"10","city_name_ar"=>"تلا","city"=>"Tala"],
            // ["id"=>"218","governorate_id"=>"10","city_name_ar"=>"الشهداء","city"=>"Al Shohada"],
            // ["id"=>"219","governorate_id"=>"11","city_name_ar"=>"المنيا","city"=>"Minya"],
            // ["id"=>"220","governorate_id"=>"11","city_name_ar"=>"المنيا الجديدة","city"=>"Minya El Gedida"],
            // ["id"=>"221","governorate_id"=>"11","city_name_ar"=>"العدوة","city"=>"El Adwa"],
            // ["id"=>"222","governorate_id"=>"11","city_name_ar"=>"مغاغة","city"=>"Magagha"],
            // ["id"=>"223","governorate_id"=>"11","city_name_ar"=>"بني مزار","city"=>"Bani Mazar"],
            // ["id"=>"224","governorate_id"=>"11","city_name_ar"=>"مطاي","city"=>"Mattay"],
            // ["id"=>"225","governorate_id"=>"11","city_name_ar"=>"سمالوط","city"=>"Samalut"],
            // ["id"=>"226","governorate_id"=>"11","city_name_ar"=>"المدينة الفكرية","city"=>"Madinat El Fekria"],
            // ["id"=>"227","governorate_id"=>"11","city_name_ar"=>"ملوي","city"=>"Meloy"],
            // ["id"=>"228","governorate_id"=>"11","city_name_ar"=>"دير مواس","city"=>"Deir Mawas"],
            // ["id"=>"229","governorate_id"=>"11","city_name_ar"=>"ابو قرقاص","city"=>"Abu Qurqas"],
            // ["id"=>"230","governorate_id"=>"11","city_name_ar"=>"ارض سلطان","city"=>"Ard Sultan"],
            // ["id"=>"231","governorate_id"=>"12","city_name_ar"=>"بنها","city"=>"Banha"],
            // ["id"=>"232","governorate_id"=>"12","city_name_ar"=>"قليوب","city"=>"Qalyub"],
            // ["id"=>"233","governorate_id"=>"12","city_name_ar"=>"شبرا الخيمة","city"=>"Shubra Al Khaimah"],
            // ["id"=>"234","governorate_id"=>"12","city_name_ar"=>"القناطر الخيرية","city"=>"Al Qanater Charity"],
            // ["id"=>"235","governorate_id"=>"12","city_name_ar"=>"الخانكة","city"=>"Khanka"],
            // ["id"=>"236","governorate_id"=>"12","city_name_ar"=>"كفر شكر","city"=>"Kafr Shukr"],
            // ["id"=>"237","governorate_id"=>"12","city_name_ar"=>"طوخ","city"=>"Tukh"],
            // ["id"=>"238","governorate_id"=>"12","city_name_ar"=>"قها","city"=>"Qaha"],
            // ["id"=>"239","governorate_id"=>"12","city_name_ar"=>"العبور","city"=>"Obour"],
            // ["id"=>"240","governorate_id"=>"12","city_name_ar"=>"الخصوص","city"=>"Khosous"],
            // ["id"=>"241","governorate_id"=>"12","city_name_ar"=>"شبين القناطر","city"=>"Shibin Al Qanater"],
            // ["id"=>"242","governorate_id"=>"12","city_name_ar"=>"مسطرد","city"=>"Mostorod"],
            // ["id"=>"243","governorate_id"=>"13","city_name_ar"=>"الخارجة","city"=>"El Kharga"],
            // ["id"=>"244","governorate_id"=>"13","city_name_ar"=>"باريس","city"=>"Paris"],
            // ["id"=>"245","governorate_id"=>"13","city_name_ar"=>"موط","city"=>"Mout"],
            ["governorate_id"=>"13","city"=>"Farafra"],
            ["governorate_id"=>"13","city"=>"Balat"],
            ["governorate_id"=>"13","city"=>"Dakhla"],
            ["governorate_id"=>"14","city"=>"Suez"],
            // ["id"=>"250","governorate_id"=>"14","city_name_ar"=>"الجناين","city"=>"Alganayen"],
            // ["id"=>"251","governorate_id"=>"14","city_name_ar"=>"عتاقة","city"=>"Ataqah"],
            // ["id"=>"252","governorate_id"=>"14","city_name_ar"=>"العين السخنة","city"=>"Ain Sokhna"],
            // ["id"=>"253","governorate_id"=>"14","city_name_ar"=>"فيصل","city"=>"Faysal"],
            // ["id"=>"254","governorate_id"=>"15","city_name_ar"=>"أسوان","city"=>"Aswan"],
            // ["id"=>"255","governorate_id"=>"15","city_name_ar"=>"أسوان الجديدة","city"=>"Aswan El Gedida"],
            // ["id"=>"256","governorate_id"=>"15","city_name_ar"=>"دراو","city"=>"Drau"],
            // ["id"=>"257","governorate_id"=>"15","city_name_ar"=>"كوم أمبو","city"=>"Kom Ombo"],
            // ["id"=>"258","governorate_id"=>"15","city_name_ar"=>"نصر النوبة","city"=>"Nasr Al Nuba"],
            // ["id"=>"259","governorate_id"=>"15","city_name_ar"=>"كلابشة","city"=>"Kalabsha"],
            // ["id"=>"260","governorate_id"=>"15","city_name_ar"=>"إدفو","city"=>"Edfu"],
            // ["id"=>"261","governorate_id"=>"15","city_name_ar"=>"الرديسية","city"=>"Al-Radisiyah"],
            ["governorate_id"=>"15","city"=>"Al Basilia"],
            ["governorate_id"=>"15","city"=>"Al Sibaeia"],
            ["governorate_id"=>"15","city"=>"Abo Simbl Al Siyahia"],
            // ["id"=>"265","governorate_id"=>"15","city_name_ar"=>"مرسى علم","city"=>"Marsa Alam"],
            // ["id"=>"266","governorate_id"=>"16","city_name_ar"=>"أسيوط","city"=>"Assiut"],
            // ["id"=>"267","governorate_id"=>"16","city_name_ar"=>"أسيوط الجديدة","city"=>"Assiut El Gedida"],
            // ["id"=>"268","governorate_id"=>"16","city_name_ar"=>"ديروط","city"=>"Dayrout"],
            // ["id"=>"269","governorate_id"=>"16","city_name_ar"=>"منفلوط","city"=>"Manfalut"],
            // ["id"=>"270","governorate_id"=>"16","city_name_ar"=>"القوصية","city"=>"Qusiya"],
            // ["id"=>"271","governorate_id"=>"16","city_name_ar"=>"أبنوب","city"=>"Abnoub"],
            // ["id"=>"272","governorate_id"=>"16","city_name_ar"=>"أبو تيج","city"=>"Abu Tig"],
            // ["id"=>"273","governorate_id"=>"16","city_name_ar"=>"الغنايم","city"=>"El Ghanaim"],
            // ["id"=>"274","governorate_id"=>"16","city_name_ar"=>"ساحل سليم","city"=>"Sahel Selim"],
            // ["id"=>"275","governorate_id"=>"16","city_name_ar"=>"البداري","city"=>"El Badari"],
            // ["id"=>"276","governorate_id"=>"16","city_name_ar"=>"صدفا","city"=>"Sidfa"],
            // ["id"=>"277","governorate_id"=>"17","city_name_ar"=>"بني سويف","city"=>"Bani Sweif"],
            ["governorate_id"=>"17","city"=>"Beni Suef El Gedida"],
            ["governorate_id"=>"17","city"=>"Al Wasta"],
            ["governorate_id"=>"17","city"=>"Naser"],
            ["governorate_id"=>"17","city"=>"Ehnasia"],
            ["governorate_id"=>"17","city"=>"beba"],
            ["governorate_id"=>"17","city"=>"Fashn"],
            ["governorate_id"=>"17","city"=>"Somasta"],
            ["governorate_id"=>"17","city"=>"Alabbaseri"],
            // ["id"=>"286","governorate_id"=>"17","city_name_ar"=>"مقبل","city"=>"Mokbel"],
            // ["id"=>"287","governorate_id"=>"18","city_name_ar"=>"بورسعيد","city"=>"PorSaid"],
            // ["id"=>"288","governorate_id"=>"18","city_name_ar"=>"بورفؤاد","city"=>"Port Fouad"],
            // ["id"=>"289","governorate_id"=>"18","city_name_ar"=>"العرب","city"=>"Alarab"],
            // ["id"=>"290","governorate_id"=>"18","city_name_ar"=>"حى الزهور","city"=>"Zohour"],
            // ["id"=>"291","governorate_id"=>"18","city_name_ar"=>"حى الشرق","city"=>"Alsharq"],
            // ["id"=>"292","governorate_id"=>"18","city_name_ar"=>"حى الضواحى","city"=>"Aldawahi"],
            // ["id"=>"293","governorate_id"=>"18","city_name_ar"=>"حى المناخ","city"=>"Almanakh"],
            // ["id"=>"294","governorate_id"=>"18","city_name_ar"=>"حى مبارك","city"=>"Mubarak"],
            // ["id"=>"295","governorate_id"=>"19","city_name_ar"=>"دمياط","city"=>"Damietta"],
            // ["id"=>"296","governorate_id"=>"19","city_name_ar"=>"دمياط الجديدة","city"=>"New Damietta"],
            // ["id"=>"297","governorate_id"=>"19","city_name_ar"=>"رأس البر","city"=>"Ras El Bar"],
            // ["id"=>"298","governorate_id"=>"19","city_name_ar"=>"فارسكور","city"=>"Faraskour"],
            // ["id"=>"299","governorate_id"=>"19","city_name_ar"=>"الزرقا","city"=>"Zarqa"],
            // ["id"=>"300","governorate_id"=>"19","city_name_ar"=>"السرو","city"=>"alsaru"],
            // ["id"=>"301","governorate_id"=>"19","city_name_ar"=>"الروضة","city"=>"alruwda"],
            // ["id"=>"302","governorate_id"=>"19","city_name_ar"=>"كفر البطيخ","city"=>"Kafr El-Batikh"],
            // ["id"=>"303","governorate_id"=>"19","city_name_ar"=>"عزبة البرج","city"=>"Azbet Al Burg"],
            // ["id"=>"304","governorate_id"=>"19","city_name_ar"=>"ميت أبو غالب","city"=>"Meet Abou Ghalib"],
            // ["id"=>"305","governorate_id"=>"19","city_name_ar"=>"كفر سعد","city"=>"Kafr Saad"],
            // ["id"=>"306","governorate_id"=>"20","city_name_ar"=>"الزقازيق","city"=>"Zagazig"],
            // ["id"=>"307","governorate_id"=>"20","city_name_ar"=>"العاشر من رمضان","city"=>"Al Ashr Men Ramadan"],
            // ["id"=>"308","governorate_id"=>"20","city_name_ar"=>"منيا القمح","city"=>"Minya Al Qamh"],
            // ["id"=>"309","governorate_id"=>"20","city_name_ar"=>"بلبيس","city"=>"Belbeis"],
            // ["id"=>"310","governorate_id"=>"20","city_name_ar"=>"مشتول السوق","city"=>"Mashtoul El Souq"],
            // ["id"=>"311","governorate_id"=>"20","city_name_ar"=>"القنايات","city"=>"Qenaiat"],
            // ["id"=>"312","governorate_id"=>"20","city_name_ar"=>"أبو حماد","city"=>"Abu Hammad"],
            // ["id"=>"313","governorate_id"=>"20","city_name_ar"=>"القرين","city"=>"El Qurain"],
            // ["id"=>"314","governorate_id"=>"20","city_name_ar"=>"ههيا","city"=>"Hehia"],
            // ["id"=>"315","governorate_id"=>"20","city_name_ar"=>"أبو كبير","city"=>"Abu Kabir"],
            // ["id"=>"316","governorate_id"=>"20","city_name_ar"=>"فاقوس","city"=>"Faccus"],
            // ["id"=>"317","governorate_id"=>"20","city_name_ar"=>"الصالحية الجديدة","city"=>"El Salihia El Gedida"],
            // ["id"=>"318","governorate_id"=>"20","city_name_ar"=>"الإبراهيمية","city"=>"Al Ibrahimiyah"],
            // ["id"=>"319","governorate_id"=>"20","city_name_ar"=>"ديرب نجم","city"=>"Deirb Negm"],
            // ["id"=>"320","governorate_id"=>"20","city_name_ar"=>"كفر صقر","city"=>"Kafr Saqr"],
            // ["id"=>"321","governorate_id"=>"20","city_name_ar"=>"أولاد صقر","city"=>"Awlad Saqr"],
            // ["id"=>"322","governorate_id"=>"20","city_name_ar"=>"الحسينية","city"=>"Husseiniya"],
            // ["id"=>"323","governorate_id"=>"20","city_name_ar"=>"صان الحجر القبلية","city"=>"san alhajar alqablia"],
            // ["id"=>"324","governorate_id"=>"20","city_name_ar"=>"منشأة أبو عمر","city"=>"Manshayat Abu Omar"],
            // ["id"=>"325","governorate_id"=>"21","city_name_ar"=>"الطور","city"=>"Al Toor"],
            // ["id"=>"326","governorate_id"=>"21","city_name_ar"=>"شرم الشيخ","city"=>"Sharm El-Shaikh"],
            // ["id"=>"327","governorate_id"=>"21","city_name_ar"=>"دهب","city"=>"Dahab"],
            // ["id"=>"328","governorate_id"=>"21","city_name_ar"=>"نويبع","city"=>"Nuweiba"],
            // ["id"=>"329","governorate_id"=>"21","city_name_ar"=>"طابا","city"=>"Taba"],
            // ["id"=>"330","governorate_id"=>"21","city_name_ar"=>"سانت كاترين","city"=>"Saint Catherine"],
            // ["id"=>"331","governorate_id"=>"21","city_name_ar"=>"أبو رديس","city"=>"Abu Redis"],
            // ["id"=>"332","governorate_id"=>"21","city_name_ar"=>"أبو زنيمة","city"=>"Abu Zenaima"],
            // ["id"=>"333","governorate_id"=>"21","city_name_ar"=>"رأس سدر","city"=>"Ras Sidr"],
            // ["id"=>"334","governorate_id"=>"22","city_name_ar"=>"كفر الشيخ","city"=>"Kafr El Sheikh"],
            // ["id"=>"335","governorate_id"=>"22","city_name_ar"=>"وسط البلد كفر الشيخ","city"=>"Kafr El Sheikh Downtown"],
            // ["id"=>"336","governorate_id"=>"22","city_name_ar"=>"دسوق","city"=>"Desouq"],
            // ["id"=>"337","governorate_id"=>"22","city_name_ar"=>"فوه","city"=>"Fooh"],
            // ["id"=>"338","governorate_id"=>"22","city_name_ar"=>"مطوبس","city"=>"Metobas"],
            // ["id"=>"339","governorate_id"=>"22","city_name_ar"=>"برج البرلس","city"=>"Burg Al Burullus"],
            // ["id"=>"340","governorate_id"=>"22","city_name_ar"=>"بلطيم","city"=>"Baltim"],
            // ["id"=>"341","governorate_id"=>"22","city_name_ar"=>"مصيف بلطيم","city"=>"Masief Baltim"],
            // ["id"=>"342","governorate_id"=>"22","city_name_ar"=>"الحامول","city"=>"Hamol"],
            // ["id"=>"343","governorate_id"=>"22","city_name_ar"=>"بيلا","city"=>"Bella"],
            // ["id"=>"344","governorate_id"=>"22","city_name_ar"=>"الرياض","city"=>"Riyadh"],
            // ["id"=>"345","governorate_id"=>"22","city_name_ar"=>"سيدي سالم","city"=>"Sidi Salm"],
            // ["id"=>"346","governorate_id"=>"22","city_name_ar"=>"قلين","city"=>"Qellen"],
            // ["id"=>"347","governorate_id"=>"22","city_name_ar"=>"سيدي غازي","city"=>"Sidi Ghazi"],
            // ["id"=>"348","governorate_id"=>"23","city_name_ar"=>"مرسى مطروح","city"=>"Marsa Matrouh"],
            // ["id"=>"349","governorate_id"=>"23","city_name_ar"=>"الحمام","city"=>"El Hamam"],
            // ["id"=>"350","governorate_id"=>"23","city_name_ar"=>"العلمين","city"=>"Alamein"],
            // ["id"=>"351","governorate_id"=>"23","city_name_ar"=>"الضبعة","city"=>"Dabaa"],
            // ["id"=>"352","governorate_id"=>"23","city_name_ar"=>"النجيلة","city"=>"Al-Nagila"],
            // ["id"=>"353","governorate_id"=>"23","city_name_ar"=>"سيدي براني","city"=>"Sidi Brani"],
            // ["id"=>"354","governorate_id"=>"23","city_name_ar"=>"السلوم","city"=>"Salloum"],
            // ["id"=>"355","governorate_id"=>"23","city_name_ar"=>"سيوة","city"=>"Siwa"],
            // ["id"=>"356","governorate_id"=>"23","city_name_ar"=>"مارينا","city"=>"Marina"],
            // ["id"=>"357","governorate_id"=>"23","city_name_ar"=>"الساحل الشمالى","city"=>"North Coast"],
            // ["id"=>"358","governorate_id"=>"24","city_name_ar"=>"الأقصر","city"=>"Luxor"],
            // ["id"=>"359","governorate_id"=>"24","city_name_ar"=>"الأقصر الجديدة","city"=>"New Luxor"],
            // ["id"=>"360","governorate_id"=>"24","city_name_ar"=>"إسنا","city"=>"Esna"],
            // ["id"=>"361","governorate_id"=>"24","city_name_ar"=>"طيبة الجديدة","city"=>"New Tiba"],
            // ["id"=>"362","governorate_id"=>"24","city_name_ar"=>"الزينية","city"=>"Al ziynia"],
            // ["id"=>"363","governorate_id"=>"24","city_name_ar"=>"البياضية","city"=>"Al Bayadieh"],
            // ["id"=>"364","governorate_id"=>"24","city_name_ar"=>"القرنة","city"=>"Al Qarna"],
            // ["id"=>"365","governorate_id"=>"24","city_name_ar"=>"أرمنت","city"=>"Armant"],
            // ["id"=>"366","governorate_id"=>"24","city_name_ar"=>"الطود","city"=>"Al Tud"],
            // ["id"=>"367","governorate_id"=>"25","city_name_ar"=>"قنا","city"=>"Qena"],
            // ["id"=>"368","governorate_id"=>"25","city_name_ar"=>"قنا الجديدة","city"=>"New Qena"],
            // ["id"=>"369","governorate_id"=>"25","city_name_ar"=>"ابو طشت","city"=>"Abu Tesht"],
            // ["id"=>"370","governorate_id"=>"25","city_name_ar"=>"نجع حمادي","city"=>"Nag Hammadi"],
            // ["id"=>"371","governorate_id"=>"25","city_name_ar"=>"دشنا","city"=>"Deshna"],
            // ["id"=>"372","governorate_id"=>"25","city_name_ar"=>"الوقف","city"=>"Alwaqf"],
            // ["id"=>"373","governorate_id"=>"25","city_name_ar"=>"قفط","city"=>"Qaft"],
            // ["id"=>"374","governorate_id"=>"25","city_name_ar"=>"نقادة","city"=>"Naqada"],
            // ["id"=>"375","governorate_id"=>"25","city_name_ar"=>"فرشوط","city"=>"Farshout"],
            // ["id"=>"376","governorate_id"=>"25","city_name_ar"=>"قوص","city"=>"Quos"],
            // ["id"=>"377","governorate_id"=>"26","city_name_ar"=>"العريش","city"=>"Arish"],
            // ["id"=>"378","governorate_id"=>"26","city_name_ar"=>"الشيخ زويد","city"=>"Sheikh Zowaid"],
            // ["id"=>"379","governorate_id"=>"26","city_name_ar"=>"نخل","city"=>"Nakhl"],
            // ["id"=>"380","governorate_id"=>"26","city_name_ar"=>"رفح","city"=>"Rafah"],
            // ["id"=>"381","governorate_id"=>"26","city_name_ar"=>"بئر العبد","city"=>"Bir al-Abed"],
            // ["id"=>"382","governorate_id"=>"26","city_name_ar"=>"الحسنة","city"=>"Al Hasana"],
            // ["id"=>"383","governorate_id"=>"27","city_name_ar"=>"سوهاج","city"=>"Sohag"],
            // ["id"=>"384","governorate_id"=>"27","city_name_ar"=>"سوهاج الجديدة","city"=>"Sohag El Gedida"],
            // ["id"=>"385","governorate_id"=>"27","city_name_ar"=>"أخميم","city"=>"Akhmeem"],
            // ["id"=>"386","governorate_id"=>"27","city_name_ar"=>"أخميم الجديدة","city"=>"Akhmim El Gedida"],
            // ["id"=>"387","governorate_id"=>"27","city_name_ar"=>"البلينا","city"=>"Albalina"],
            // ["id"=>"388","governorate_id"=>"27","city_name_ar"=>"المراغة","city"=>"El Maragha"],
            // ["id"=>"389","governorate_id"=>"27","city_name_ar"=>"المنشأة","city"=>"almunsha'a"],
            // ["id"=>"390","governorate_id"=>"27","city_name_ar"=>"دار السلام","city"=>"Dar AISalaam"],
            // ["id"=>"391","governorate_id"=>"27","city_name_ar"=>"جرجا","city"=>"Gerga"],
            // ["id"=>"392","governorate_id"=>"27","city_name_ar"=>"جهينة الغربية","city"=>"Jahina Al Gharbia"],
            // ["id"=>"393","governorate_id"=>"27","city_name_ar"=>"ساقلته","city"=>"Saqilatuh"],
            // ["id"=>"394","governorate_id"=>"27","city_name_ar"=>"طما","city"=>"Tama"],
            // ["id"=>"395","governorate_id"=>"27","city_name_ar"=>"طهطا","city"=>"Tahta"],
            // ["id"=>"396","governorate_id"=>"27","city_name_ar"=>"الكوثر","city"=>"Alkawthar"]
        ];

        foreach ($cities as $city) {
            City::create(
                [
                    'governorate_id' => $city['governorate_id'],
                    'name' => $city['city'],
                ],
            );
        }
    }
}
